import Head from 'next/head';
import Header from '../src/components/Head/Header';
import FeaturedProducts from '../src/components/Products/Carousels/FeaturedProducts';
import LastProducts from '../src/components/Products/Carousels/LastProducts';
import { getFeaturedProducts, getLastProducts, getCategories } from './api/dato-cms';
import Script from 'next/script';
import Footer from '../src/components/Footer/Footer';
import 'bootstrap/dist/css/bootstrap.css';


export async function getStaticProps() {
  const featuredProducts = await getFeaturedProducts();
  const lastProducts = await getLastProducts();
  const categories = await getCategories();


  return {
    props: {
      featured: featuredProducts,
      last: lastProducts,
      cat: categories,
    },
    revalidate: 3600
  }
};

export default function Home({ featured, last, cat }) {

  return (
    <div className="main">
      <Head>
        <title>iMall 071</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="/nprogress.css"></link>
      </Head>
      <main>
      <Header cat={cat} />
        <div className="section">
          <div className="container">
            <FeaturedProducts featured={featured} />
            <LastProducts last={last} />
          </div>
        </div>
       </main>   
          <Footer />
            <Script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></Script>
            <Script src="https://kit.fontawesome.com/33c943d672.js" crossorigin="anonymous"></Script>
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossOrigin="anonymous"></Script>
          </div>
  );
}
