import Head from 'next/head';
import Header from '../../src/components/Head/Header';
import Script from 'next/script';
import { getCategories, getCategoryProducts, getFilterCategories, getFilterCategoriesProduct } from '../api/dato-cms';
import Footer from '../../src/components/Footer/Footer';
import 'bootstrap/dist/css/bootstrap.css';
import {New, Showcase, Used} from "../../src/components/Products/Item/Status";
import Link from 'next/link';


export async function getStaticPaths() {
    return {
        paths: [{
            params: {
                slug: '/'
            }
        }],
        fallback: 'blocking'
    }
}

export async function getStaticProps(context) {
    const slug = await getFilterCategories(context.params.slug);
    const categories = await getCategories();
    if(slug.length <= 0) {
        const error = "Nenhuma categoria encontrada";
        return {
            props: {
                error: error,
                cat: categories
            }
        }
    } else {
    const product = await getFilterCategoriesProduct(slug[0].id);

    return {
        props: {
            product: product,
            cat: categories,
            slug: slug
        },
        revalidate: 3600
    }
}
};

export function ProductCategory({ cat, product, slug, error}){

    const changePrice = (num) => {
        let preco = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(num);
        return preco;
    }

    const productState = (state) => {

        if (state === 'novo') {
            return <New/>;
        }

        if (state === 'vitrine') {
            return <Showcase/>;
        }

        if (state === 'usado') {
            return <Used/>;
        }
    }


    if (error) return (
        <div>
        <Head>
                <title>Categoria não encontrada</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header cat={cat} />
            <main className="container-fluid pt-5 pb-5 text-center">
               <div className="container text-center">
                   Categoria não encontrada.
               </div>
            </main>
            <Footer/>
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossOrigin="anonymous"></Script>
    </div>
    )
    return(
        <div>
        <Head>
                <title>Categoria - {slug[0].categoryTitle}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header cat={cat} />
            <main className="container-fluid pt-5 pb-5">
               <div className="container">
                   <h1 className="text-center fs-4">Categoria: {slug[0].categoryTitle}</h1>
               <div className="row justify-content-md-center">
                   {product.map(item=>(
                       <Link href={`/produto/${item.slug}`} key={item.title}>
                       <div className="col-sm-12 col-md-4 col-lg-3 col-xl-3 content-product-info m-2 cursor-pointer logo">
                           <img src={item.featuredImage.url}/>
                           <div className="product-info text-center">
                           <p className="text-center">{item.title}</p>
                           <span className="product-price mb-2 text-center">{changePrice(item.preco)}</span>
                           <div className="justify-content-md-center">{productState(item.productState)}</div>
                           </div>
                       </div>
                       </Link>
                   ))}
               </div>
               </div>
            </main>
            <Footer/>
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossOrigin="anonymous"></Script>
    </div>
    )

}


export default ProductCategory;