import Head from 'next/head';
import Header from '../../components/Header';
import Script from 'next/script';
import { getCategories, getFilterProducts } from '../../components/dato-cms';
import ProductItem from '../../components/ProductItem';


const Product = ({ cat, product }) => (
    <div>
        <Head>
            <title>iMall 071</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header cat={cat} />
        <div className="w-auto bg-gray-200">

            <main className="container">
                {product.map(item => (
                    <div>
                        <ProductItem
                            title={item.title}
                            state={item.productState}
                            key={item.id}
                            image={item.featuredImage.url}
                            shortDesc={item.shortDescription}
                            gallery={item.gallery}
                        />
                    </div>
                ))}
            </main>

            <footer>
                <span>iMall071</span>
            </footer>
            <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossOrigin="anonymous"></Script>
        </div>
    </div>
);

export async function getServerSideProps(context) {
    const response = await getFilterProducts(context.params.id);
    const categories = await getCategories();

    return {
        props: {
            product: response,
            cat: categories
        }
    }
};


export default Product;